language: node_js
node_js:
- '8.0.0'
- '12.0.0'
os:
  - linux
  - osx
  - windows
deploy:
  provider: npm
  email: corey@coreybutler.com
  api_key:
    secure: IXATJk85IFBw2DHIby3q0MggdHBTcw9ZDomMcN2MVeOaE0/MN3C4gAkdLo5klVLaXdGi2HMVkPKn2C1RNkuGV8wuOhjQQyUvsm3phL1aTvwwVlTAQmtR+yVDRaijUzj6RsbngMw+JraJzSJKUg46cfLRNZj7JT9CM3ns7JH4mbE=
  on:
    tags: true
    repo: coreybutler/shortbus
